"""empty message

Revision ID: 032e5f933dd3
Revises: 5878812f12ad
Create Date: 2020-10-20 20:02:00.925410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '032e5f933dd3'
down_revision = '5878812f12ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teste_db_2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endereco', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teste_db_2_endereco'), 'teste_db_2', ['endereco'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teste_db_2_endereco'), table_name='teste_db_2')
    op.drop_table('teste_db_2')
    # ### end Alembic commands ###
